### ISSUE TITLE
Tulpar is not working at all !!

### ISSUE THREAD

**Issue by sasatefa2009** [anilbaranyelken/tulpar#3]
here is the outputwhen i try with python3

python3 tulpar.py full google.com
  File "tulpar.py", line 110
    print "[+]Domain: ", query.domain
                      ^
SyntaxError: Missing parentheses in call to 'print'

---------------------------------------------------------
and when i try with python2

python2 tulpar.py full google.com
Traceback (most recent call last):
File "tulpar.py", line 557, in <module>
print str(url).split("/")[2]
IndexError: list index out of range
---------------------------------------------------------------
when i try python3 tulpar.py -h

i get this

python tulpar.py -h
File "tulpar.py", line 110
print "[+]Domain: ", query.domain
                      ^
SyntaxError: Missing parentheses in call to 'print'

and when i try with python2 i get the help instructions but with a full page of zero and ones before it

**Comment by ghost** [comment]
Hi,

This program works with Python 2.7. If it is possible, could you please
 try  with Python 2.7?

Best regards...

2017-09-02 11:52 GMT+03:00 sasatefa2009 <notifications@github.com>:

**Comment by sasatefa2009** [comment]
@anilbaranyelken 

that's what i get

python2 tulpar.py full google.com
Traceback (most recent call last):
File "tulpar.py", line 557, in
print str(url).split("/")[2]
IndexError: list index out of range

**Comment by lianfeng30** [comment]
i hava same problem
python2 tulpar.py full Google.com
Traceback (most recent call last):
  File "tulpar.py", line 557, in <module>
    print str(url).split("/")[2]
IndexError: list index out of range

**Comment by ghost** [comment]
If it is possible, could you please try following command:
python2 tulpar.py full https://google.com

**Comment by sasatefa2009** [comment]
@anilbaranyelken 
got this error

```
Traceback (most recent call last):
  File "tulpar.py", line 636, in <module>
    whoisSorgu(url,dosyaAdi)
  File "tulpar.py", line 109, in whoisSorgu
    query = whois.whois(url)
AttributeError: 'module' object has no attribute 'whois'

```

**Comment by ghost** [comment]
Hi,

Could you please install whois module?
pip install whois

Best regards...

2017-09-04 17:17 GMT+03:00 Mostafa Nafady <notifications@github.com>:

**Comment by sasatefa2009** [comment]
Greetings,

Still the same problem

**Comment by ghost** [comment]
Hi,

If it is possible, could you please install python-whois with pip?

Best regards...

2017-09-04 17:56 GMT+03:00 Mostafa Nafady <notifications@github.com>:

**Comment by sasatefa2009** [comment]
@anilbaranyelken 

already had it and updated.
and still the same problem

**Comment by ghost** [comment]
Hi,

If it is possible, could you remove all whois module your system? After
maybe you will install only python-whois module.

Best regards...

2017-09-04 18:10 GMT+03:00 Mostafa Nafady <notifications@github.com>:

**Comment by sasatefa2009** [comment]
pip list is that the way to get all the whois ?
and what is the good way to delete them " pip uninstall" ??

**Comment by sasatefa2009** [comment]
update:

i uninstalled three whois libraries using pip uninstall and then installed python-whois but still the same problem.

is it 'python-whois' or 'whois' to install ? 
i already installed 'python-whois' as you said

**Comment by ghost** [comment]
Hi,

Could you please download following link?

https://pypi.python.org/pypi/python-whois

And you could run following command:

python2.7 setup.py install

If it is possible, could you please send your screenshot is about this
issue?

Best regards...

2017-09-04 18:41 GMT+03:00 Mostafa Nafady <notifications@github.com>:

**Comment by sasatefa2009** [comment]
first screenshot of tulpar and installation
![screenshot from 2017-09-05 03-18-51](https://user-images.githubusercontent.com/22708418/30041283-14386440-91e9-11e7-8a82-fec45dc3512d.png)

second screenshot of tulpar and installation
![screenshot from 2017-09-05 03-19-16](https://user-images.githubusercontent.com/22708418/30041294-27fb1f04-91e9-11e7-9e1e-15831a574f1a.png)

**Comment by sasatefa2009** [comment]
here is the output of " pip list'
AdvancedHTTPServer (2.0.10)
aiohttp (2.2.3)
alembic (0.8.8.dev0)
argh (0.26.2)
arpreq (0.3.1)
asn1crypto (0.22.0)
async-timeout (1.3.0)
basemap (1.0.7)
beautifulsoup4 (4.4.1)
bintrees (2.0.7)
binwalk (2.1.1)
bitarray (0.8.1)
blinker (1.4)
boltons (16.4.1)
Brlapi (0.6.5)
brotlipy (0.6.0)
certifi (2017.4.17)
cffi (1.10.0)
chardet (3.0.4)
chrome-gnome-shell (0.0.0)
click (6.7)
cluster (1.4.0)
colorama (0.3.3)
construct (2.8.14)
crcelk (1.1)
cryptography (1.9)
cssutils (1.0.2)
cupshelpers (1.0)
cycler (0.10.0)
debtags (2.1)
decorator (4.1.1)
dnspython (1.15.0)
EditorConfig (0.12.1)
Flask (0.12.2)
future (0.16.0)
futures (3.1.1)
geoip2 (2.5.0)
geojson (1.3.4)
gitdb2 (2.0.2)
GitPython (2.1.5)
graphene (1.1.3)
graphene-sqlalchemy (1.1.1)
graphql-core (1.0.1)
graphql-relay (0.4.5)
guess-language (0.2)
h2 (2.6.2)
hashID (3.1.4)
hpack (3.0.0)
html2text (2016.9.19)
html5lib (0.999999999)
httplib2 (0.9.2)
hyperframe (4.0.2)
icalendar (3.8)
idna (2.5)
iso8601 (0.1.11)
itsdangerous (0.24)
Jinja2 (2.9.6)
jsbeautifier (1.6.14)
jsonpickle (0.9.2)
kaitaistruct (0.6)
keyring (10.4.0)
keyrings.alt (2.2)
louis (3.0.0)
lxml (3.8.0)
Mako (1.0.7)
Markdown (2.6.9)
MarkupSafe (1.0)
matplotlib (2.0.0)
maxminddb (1.3.0)
minepy (1.0.0)
mitmproxy (2.0.2)
msgpack-python (0.4.8)
multidict (3.1.3)
names (0.3.0)
ndg-httpsclient (0.4.3)
netaddr (0.7.18)
Netzob (1.0.2)
nili (0.1)
nltk (3.2.4)
numpy (1.12.1)
olefile (0.44)
paramiko (2.0.0)
passlib (1.7.1)
pathtools (0.1.2)
pcapy (0.10.10)
phply (1.0.0)
Pillow (4.2.1)
pip (9.0.1)
plecost (1.1.1)
pluginbase (0.3)
ply (3.10)
promise (1.0.1)
psutil (5.3.0)
psycopg2 (2.7.3)
pyasn1 (0.3.3)
pybloomfiltermmap (0.3.15)
pyClamd (0.4.0)
pycparser (2.18)
pycrypto (2.6.1)
pycryptodome (3.4.7)
pycups (1.9.73)
pycurl (7.43.0)
PyGithub (1.35)
pygobject (3.22.0)
PyJWT (1.5.2)
PyOpenGL (3.1.0)
pyOpenSSL (17.2.0)
pyotp (2.2.1)
pyparsing (2.1.10)
pyperclip (1.5.27)
pyqtgraph (0.10.0)
pyserial (3.4)
pysmbc (1.0.15.6)
pysmi (0.1.3)
pysnmp (4.3.9)
PySocks (1.6.7)
python-apt (1.4.0b3+b1)
python-dateutil (2.6.1)
python-debian (0.1.30)
python-debianbts (2.6.1)
python-editor (0.4)
python-nmap (0.6.1)
python-ntlm (1.1.0)
python-pam (1.8.2)
python-whois (0.6.5)
pytz (2017.2)
pyxdg (0.25)
PyYAML (3.12)
reportbug (7.1.7)
requests (2.18.1)
requests-file (1.4.2)
ruamel.yaml (0.13.14)
scapy-python3 (0.21)
scapy-real (2.2.0.dev0)
scipy (0.18.1)
SecretStorage (2.3.1)
setuptools (36.2.7)
six (1.10.0)
smmap2 (2.0.3)
smoke-zephyr (1.0.2)
sortedcontainers (1.5.7)
SQLAlchemy (1.1.11)
tabulate (0.7.7)
tblib (1.3.2)
termcolor (1.1.0)
terminaltables (3.1.0)
termineter (0.2.7)
tldextract (2.1.0)
tornado (4.4.3)
tzlocal (1.4)
unattended-upgrades (0.1)
urllib3 (1.21.1)
urwid (1.3.1)
virtualenv (15.1.0)
wafw00f (0.9.4)
watchdog (0.8.3)
webencodings (0.5.1)
websocket-client (0.37.0)
Werkzeug (0.12.2)
wheel (0.29.0)
xlrd (1.1.0)
XlsxWriter (0.9.6)
yarl (0.12.0)

**Comment by sasatefa2009** [comment]
I FOUND THE PROBLEM

THE 'whois' library wasn't un-installed, even though i un-installed it
so i deleted it manually now it works very well.
but another two problems came

first one

/usr/local/lib/python2.7/dist-packages/urllib3-dev-py2.7.egg/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)

this is the fix of this problem, hover down a little for python2
`https://urllib3.readthedocs.io/en/latest/user-guide.html#ssl`

**i found that you even got the same thing when you tried " python tulpar.py cyberthreatintelligence http://google.com " in the "usage" file**

second problem
```

+]Server:  gws
[+]Technology: 
Traceback (most recent call last):
  File "tulpar.py", line 643, in <module>
    headerInformation(url,dosyaAdi)
  File "tulpar.py", line 201, in headerInformation
    print "[+]Technology: ", sonuc.headers['X-Powered-By']
  File "/usr/lib/python2.7/dist-packages/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'x-powered-by'

```

**Comment by lianfeng30** [comment]
i have same problem:

  InsecureRequestWarning)
/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:791: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
[+]Server:  nginx
[+]Technology:
Traceback (most recent call last):
  File "tulpar.py", line 643, in <module>
    headerInformation(url,dosyaAdi)
  File "tulpar.py", line 201, in headerInformation
    print "[+]Technology: ", sonuc.headers['X-Powered-By']
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'x-powered-by'

**Comment by lianfeng30** [comment]
There is another error：

[+] Encoded URL:% 68% 74% 74% 70% 73% 3A% 2F% 2F% 6D% 6F% 62% 69% 6B% 65% 2E% 63% 6F% 6D
/library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:791: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly recommended See: https://urllib3.readthedocs.org/en/latest/security.html
   InsecureRequestWarning)
/library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:791: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly recommended See: https://urllib3.readthedocs.org/en/latest/security.html
   InsecureRequestWarning)

**Comment by lianfeng30** [comment]
Please fix it
Thank you
